tools:
  - class_name: "verl.tools.sandbox_fusion_tools.SandboxFusionTool"
    config: 
      sandbox_fusion_url: "http://210.28.135.36:8080/run_code"
      num_workers: 10
      enable_global_rate_limit: true
      rate_limit: 10
      default_timeout: 30
      default_language: "python"

    tool_schema:
      type: "function"
      function:
        name: "python_interpreter"
        description: "A Python code interpreter that can execute Python code and return the results. Use this tool to run Python code, perform calculations, data analysis, create visualizations, or solve programming problems step by step."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "The Python code to execute. Can include imports, variable definitions, calculations, function definitions, and any valid Python statements."
          required: ["code"]