hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 2048
  max_response_length: 2048
  train_batch_size: 128
  return_raw_chat: True

actor_rollout_ref:
  hybrid_engine: True
  rollout:
    name: sglang
    multi_turn:
      enable: True
      max_turns: 8
      tool_config_path: "./config/tool_config/aime24_retool_config.yaml"
      use_inference_chat_template: True
      enable_tokenization_sanity_check: True
      tool_call_parser: "retool"