hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 8192
  max_response_length: 8192
  train_batch_size: 64
  return_raw_chat: True
  train_files: /data2/lixy/VerlCoder/data/retool_dapo_split/train.parquet
  val_files: /data2/lixy/VerlCoder/data/retool_dapo_split/val.parquet

actor_rollout_ref:
  hybrid_engine: True
  nccl_timeout: 600
  model:
    path: /data2/lixy/VerlCoder/checkpoints/retool-multiturn-sft/retool-multiturn-sft-qwen2.5-7b-sp4-lr5e-6/global_step_42
    trust_remote_code: True
    enable_gradient_checkpointing: True
    use_remove_padding: True
  rollout:
    name: sglang
    log_prob_micro_batch_size_per_gpu: 2
    gpu_memory_utilization: 0.6
    free_cache_engine: True
    max_num_batched_tokens: 4096
    multi_turn:
      enable: True
      max_assistant_turns: 8
      max_user_turns: 8
      tool_config_path: /home/lixy/workspace/VerlCoder/verl/recipe/retool/config/tool_config/retool.yaml
  actor:
    optim:
      lr: 5e-7
    ppo_mini_batch_size: 64
    ppo_micro_batch_size_per_gpu: 2
    use_kl_loss: True
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    entropy_coeff: 0.01
    use_dynamic_bsz: True
    ppo_max_token_len_per_gpu: 8192
    ulysses_sequence_parallel_size: 2
    entropy_from_logits_with_chunking: True
    entropy_checkpointing: True
    strategy: fsdp2
    fsdp_config:
      param_offload: False
      optimizer_offload: False
      reshard_after_forward: True
      offload_policy: False
  ref:
    log_prob_micro_batch_size_per_gpu: 2
    ulysses_sequence_parallel_size: 2
    log_prob_use_dynamic_bsz: True
    log_prob_max_token_len_per_gpu: 8192
    entropy_from_logits_with_chunking: True
    entropy_checkpointing: True
    strategy: fsdp2
    fsdp_config:
      param_offload: False
      reshard_after_forward: True
      offload_policy: False

algorithm:
  adv_estimator: grpo
  use_kl_in_reward: False

trainer:
  critic_warmup: 0
  logger: ['console', 'swanlab']
  project_name: 'retool_grpo'
  experiment_name: 'retool-grpo-qwen2.5-7b-v1'
  n_gpus_per_node: 8
  nnodes: 1
  save_freq: 50
  test_freq: 50
  total_training_steps: 500
  val_before_train: False
  default_local_dir: /data2/lixy/VerlCoder/checkpoints/retool-grpo