hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  max_prompt_length: 8192
  max_response_length: 8192
  train_batch_size: 256
  return_raw_chat: True
  train_files: ${data.train_files}  # Override via command line
  val_files: ${data.val_files}      # Override via command line

actor_rollout_ref:
  hybrid_engine: True
  model:
    path: ${actor_rollout_ref.model.path}  # Override via command line
    trust_remote_code: True
  rollout:
    name: sglang
    multi_turn:
      enable: True
      max_assistant_turns: 8
      max_user_turns: 8
      tool_config_path: ./recipe/retool/config/tool_config/retool.yaml

algorithm:
  adv_estimator: grpo
  use_kl_in_reward: False

trainer:
  critic_warmup: 0
  logger: ['console', 'swanlab']
  project_name: 'retool_grpo'
  experiment_name: ${trainer.experiment_name}  # Override via command line
  n_gpus_per_node: 8
  nnodes: 1
  save_freq: 20
  test_freq: 20
  total_training_steps: 100
  val_before_train: False
  default_local_dir: ${trainer.default_local_dir}  # Override via command line