tools:
  - class_name: "verl.tools.aime24_retool.AIME24ReTool"
    config: 
      timeout: 30
      max_code_length: 10000
    tool_schema:
      type: "function"
      function:
        name: "execute_python"
        description: "Execute Python code to help solve mathematical problems. The code will be run in a safe environment and the output will be returned."
        parameters:
          type: "object"
          properties:
            code:
              type: "string"
              description: "Python code to execute"
          required: ["code"]